/**
 * @file Automatically generated by barrelsby.
 */

export * from "./answer/answer.resolver";
export * from "./auth/auth.resolver";
export * from "./player/player.resolver";
export * from "./user/user.resolver";
