/**
 * @file Automatically generated by barrelsby.
 */

export * from "./modules/answer/repositories/answer.repository";
export * from "./modules/auth/repositories/auth.repository";
export * from "./modules/player/repositories/player.repository";
export * from "./modules/user/repositories/user.repository";
